#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      exec dnsmasq -d -p 5353 --no-hosts --domain-needed --bogus-priv --log-queries --log-facility=- \
        --local="/consul/127.0.0.1#8600"  \
        --address="/nih/172.28.128.1" \
        -r "$shome/etc/resolv.google"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
