#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      local ip_consul="$(ping -c 1 -t 1 consul | awk '$1 == "PING" { print $3 }' | perl -pe 's{[():]}{}g')" # TODO can dnsmasq use a name
      exec dnsmasq -d -p 5353 --no-hosts --domain-needed --bogus-priv --log-queries --log-facility=- \
        --local="/consul/${ip_consul}#8600"  \
        --address="/cache.nih/172.28.128.1" \
        -r "$shome/etc/resolv.google"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
