#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$(type -P dnsmasq)" ]]; then
    if [[ -x "$(type -P named)" ]]; then
      return 1
    fi
  fi
  
  return 0
}

source sub "$0" "$@"
